### ISSUE TITLE
2.5.0 - When playing an album in Files (not Library) mode, tracks from album are loaded in random order

### ISSUE THREAD

**Issue by PinkFreud** [xbmc/Kore#706] opened 2020-02-02 23:52 UTC
If I'm not using Library mode (I haven't bothered, for various reasons, preferring to stick to Files mode!), selecting an album in Kore to play causes tracks to load in an unpredictable, random order.

This is unexpected - as late as 2.4.7, tracks in File mode would load in filename order, which is the behavior that I'm expecting from 2.5.0.

Downgrading to 2.4.7 resolves the issue, but I'd prefer to be able to update Kore, while not having to worry about tracks being added to the playlist in random order.

**Comment by poisdeux** [comment] 2020-02-04 20:09
I am unable to reproduce the reported behaviour. The code regarding sorting was changed in #653 and has been explicitly set to use the path for ordering. In my setup it does sort the files on filename.

![image](https://user-images.githubusercontent.com/4527626/73781772-22544700-4791-11ea-9b5a-a3861944ac4e.png)

@SyncedSynapse any ideas?

**Comment by PinkFreud** [comment] 2020-02-12 03:50
2.5.0:
![Screenshot_20200211-224210](https://user-images.githubusercontent.com/6100139/74301359-df5e1a80-4d20-11ea-885a-6c9a1987a998.png)

Files on fileserver:
![Screenshot_20200211-224301](https://user-images.githubusercontent.com/6100139/74301373-e38a3800-4d20-11ea-8858-8a23a6ae4fe5.png)

Files in playlist in random order:
![Screenshot_20200211-224411](https://user-images.githubusercontent.com/6100139/74301375-e553fb80-4d20-11ea-86f8-e2602e24cc10.png)

**Comment by poisdeux** [comment] 2020-02-15 19:37
Ah thx. Didn't realise that you were referring to the actual playlist order.
This seems to be caused by a race condition. Should be fixed in PR #713

**Closed** 2020-02-20 19:53 UTC
