### ISSUE TITLE
Incomplete library

### ISSUE THREAD

**Issue by juup** [xbmc/Kore#219] opened 2016-03-08 09:32 UTC
Sorry, I'm not sure where the right place is to post the issue. I found similar post in the [forum](http://forum.kodi.tv/showthread.php?tid=251897&pid=2273589#pid2273589), but issue tracker from F-Droid linked here.

Since update to Jarvis the music library is incomplete.
I've already tried different servers (Raspberry Pi and Linux Mint), and deleted the list and rescan it on server. There are lot of albums missing in the remote app after update the list. 
The "Browser Library" seems to be complete, so I guess the remote app have some trouble.

Version v2.0.0

**Comment by poisdeux** [comment] 2016-04-01 16:07
I can confirm I have the same issue with my OSMC setup. I have not yet been able to reproduce this on my dev/test setup. Still working on it.
@SyncedSynapse do you have any idea what might be causing this?

**Comment by SyncedSynapse** [comment] 2016-04-01 18:12
@poisdeux No, but it would be useful if you could run a debug version of Kore connected to your OSMC, do a library sync and check the log. The relevant code is in `LibrarySyncService.java` and it contains some log messages that might be useful.

IT syncs albums/artists/songs in chunks, 300 for artist/albums, 600 for songs, so i would keep an eye on the log to check if it reached the end. If the issue is on Kore's side it should just blow up, but maybe it just isn't receiving all the data from Kodi. To check that, sending a HTTP request to OSMC would help. Something like this (didn't test it, you will get some examples on the debug log):
`{
    "jsonrpc": "2.0",
    "method": "AudioLibrary.GetAlbums",
    "id": 32,
    "params": {
        "limits": {"start": 0, "end": 300}
        "properties": ["title", "description", "artist", "genre"]
    }
}
`

**Comment by SyncedSynapse** [comment] 2016-05-25 18:44
Should be fixed (in development version). If not, please reopen.

**Closed by SyncedSynapse** 2016-05-25 18:44 UTC
