### ISSUE TITLE
port 9090

### ISSUE THREAD

**Issue by phggrue** [xbmc/Kore#452] opened 2017-09-19 16:16 UTC
I have Kodi on Linux Mint 17.3. There is a Firewall enabled with all incoming dienied.
I opened port 8080 with the IP adress of my Tablet I use for kodi remote. I also have to open port 9090, but I have to open it to all incoming. What is/are the IP adress/adresses? I tried the localhost IP and the tablet IP, no connection possible.

**Comment by poisdeux** [comment] 2017-09-20 08:19
Probably return traffic that is still getting blocked when not opening port 9090 to all incoming traffic.
Could you copy/paste your firewall configuration? I might be able to pinpoint the cause.

**Comment by SyncedSynapse** [comment] 2017-09-20 16:24
Port 9090 is to the TCP connection, which sends and receives traffic from your Kodi machine. It receives notifications regarding the play state.

You might also want to open port 9777 on your Kodi machine, to allow the EventServer connection (allows you to use the skip function in the remote).

Closing this, as this doesn't seem to be an issue. If i've misunderstood it, please reopen it.

**Closed by SyncedSynapse** 2017-09-20 16:24 UTC

**Comment by phggrue** [comment] 2017-09-20 19:59
Maybe it's not an issue.

But maybe you understand what I mean with this, I don't want any "ALLOW IN
Anywhere" in my Firewall.
I would like to know the IP(s) to set in my Firewall.

phg@phg-Aspire-ES1-131 ~ $ sudo netstat -tanpu | grep ":9090"
[sudo] password for phg:
tcp6       0      0 :::9090                 :::*                    LISTEN
    4339/kodi.bin
tcp6       0      0 192.168.1.101:9090      192.168.1.104:42615
 VERBUNDEN   4339/kodi.bin

(VERBUNDEN=CONNECTED)

This Firewall settings works, but with "ALLOW IN Anywhere"


Deny (incoming) allow (outgoing)

9090                       ALLOW IN    Anywhere
192.168.1.122 8080         ALLOW IN    192.168.1.100 8080
9090 (v6)                  ALLOW IN    Anywhere (v6)

Thank you for your effort.


2017-09-20 18:24 GMT+02:00 Synced Synapse <notifications@github.com>:

**Comment by poisdeux** [comment] 2017-09-22 06:27
If that is all that's set on your firewall than I don't see anything wrong with it. Only thing I can think of is that your devices don't get a static IP address and you should add the range of IP addresses from your DHCP server (WIFI accesspoint?) to your firewall for port 9090. 
Another solution would be to configure your router/access point to serve static IP addresses for devices that need it. In this case those running Kore. Than you only need to add those IP addresses.
Hope this helps.

**Comment by phggrue** [comment] 2017-09-22 08:58
Thankx for your answer.
I got a solution from the internet and changed it a bit:


sudo ufw allow from 192.168.1.0/24 to any port 9090 proto tcp

sudo ufw allow from 192.168.1.0/24 to any port 8080

sudo ufw allow from 192.168.1.0/24 to any port 9777
(maybe: sudo ufw allow from 192.168.1.0/24 to any port 9777 *proto tcp* - I
am not at home with my linux with Kodi)

Because all incoming is denied (but internet works) this should be a save
solution, only IPs from the local network
can connect to this ports. 192.168.1.0/24 is the range of my possible local
IPs - maybe on some rare other setups they are different.


For second sudo you can also try:


sudo ufw allow from 192.168.1.0/24 to any port 8080 proto tcp
If the previous doesn't work, delete it, and try this
sudo ufw allow from 192.168.1.0/24 to any port 8080 proto udp
otherwise see above



Thanks again, works nice!





2017-09-22 8:27 GMT+02:00 Martijn Brekhof <notifications@github.com>:
