### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Robigus92** [xbmc/Kore#514] opened 2018-02-23 09:57 UTC
Memory Leak 1

After a double rotation of the MusicActivity there are 2 instances more of:

class org.xbmc.kore.ui.sections.audio.ArtistListFragment @ 0x12cfec00
class org.xbmc.kore.ui.generic.NavigationDrawerFragment @ 0x12d00400
class org.xbmc.kore.ui.sections.audio.AlbumListFragment @ 0x12d0b400

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. 

----
Memory Leak 2

After a double rotation of the MoviesActivity there are 2 instances more of:

class org.xbmc.kore.ui.generic.NavigationDrawerFragment @ 0x12cfc400
class org.xbmc.kore.ui.sections.video.MovieListFragment @ 0x12d05800

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. 

---
Memory Leak 3

After a double rotation of the TVShowsActivity there are 2 instances more of:

class org.xbmc.kore.ui.generic.NavigationDrawerFragment @ 0x12cff400
class org.xbmc.kore.ui.sections.video.TVShowListFragment @ 0x12d06800

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well.

**Comment by poisdeux** [comment] 2018-02-23 10:32
Thx for reporting this. Do note that it is only a memory leak if we keep a reference to the objects which won't allow the garbage collector to clean up. Is that the case? And if so will you fix it or do you expect us to fix it?

**Comment by Robigus92** [comment] 2018-02-23 12:28
I have developed an automated Memory Leak detection tool which test Activities executing different lifecycle events (rotations, background-foreground, dialog pop-up events) then forcing an ending Garbage Collections. The idea is that the activity lifecycles are well managed there should not be an increase of the used heap memory.

In your activities, rotation events seem to cause an increasing trend of many Fragments usage. 
Is that correct? Old Fragments should not be removed?

**Comment by poisdeux** [comment] 2018-02-23 15:35
I just ran a test together with a memory profiler and indeed there seems to be a problem with increased heap memory usage. Unfortunately it didn't make clear what is causing the increased usage. Under normal usage patterns this will probably not cause any problems. Depending on the device it requires a couple of thousand rotations before the app actually crashes. 
But it would be good if we fix this nonetheless. Can you provide a more detailed analysis to better pinpoint the cause of the increased heap usage?

**Comment by SyncedSynapse** [comment] 2018-02-23 17:25
He's probably hitting the classic Java non-static inner class/outer class leak.

For instance, the callbacks are usually anonymous classes, so they keep a reference to the enclosing activity/fragment. These callbacks are passed to the `HostConnection` which keeps them while it is waiting for a response from the host, thereby also keeping the activity/fragment alive. When a response is obtained (success or error), the callback is "freed", which allows the GC to collect it and the enclosing activity/fragment.

This can also happen in other places, pretty well hidden: i was just looking at the sync process that gets started when the movies/tv shows/etc activity starts, and they create `RefreshItem`s, which get passed to the `EventBus`, wich will only free them when the sync process ends.

So these are temporary leaks (but leaks nonetheless). Changing this would be quite tiresome: using only static inner classes, so they don't hold references to the outer activity/fragment, and if/when they need to update views on the outer activity/fragment, we need to pass them on the constructor and only use WekReferences so they don't hold up the outer class...

As far as i can tell, there aren't permanent leaks, but i can't be 100% sure. If there are permantent leaks we should definitely identify and fix them. The temporary ones, i'm not sure if the trouble would be worth it.

**Comment by Robigus92** [comment] 2018-02-23 17:39
I have done my test setting a wait time of 0.7 seconds from a rotation to another. 

Executing 100 rotations I have seen a linear increase of the Shallow Heap and distance number allocated in heap memory. If they were temporary leaks, I should not have seen a decrease of them?

I could not say as well if they are 100% Memory Leaks or not.

**Comment by Robigus92** [comment] 2018-02-23 19:24
I have tested HostManagerActivity, AddHostActivity, MoviesActivity, TVShowsActivity, MusicActivity, AddonsActivity, FileActivity and PVRActivity.

I have found possible leaks only in the activities reported in the first post.

**Comment by SyncedSynapse** [comment] 2018-02-26 20:08
https://github.com/xbmc/Kore/commit/2206b90592bf758135586529998d3eb6d4c4ad97  should fix this. A build will be available soon [here](http://mirrors.kodi.tv/tools/kore/nightlies/).

**Comment by SyncedSynapse** [comment] 2018-02-26 20:08
Closing this for now. If you found something else, please reopen it.

**Closed by SyncedSynapse** 2018-02-26 20:08 UTC
