### ISSUE TITLE
crash on volume change

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#557] opened 2018-06-09 21:38 UTC
After the update to 2.4.0 the app crashes when using the volume up/down buttons repeatedly:

```
6-09 22:46:22.635 10235 10235 D AndroidRuntime: Shutting down VM
06-09 22:46:22.636 10235 10235 E AndroidRuntime: FATAL EXCEPTION: main
06-09 22:46:22.636 10235 10235 E AndroidRuntime: Process: org.xbmc.kore, PID: 10235
06-09 22:46:22.636 10235 10235 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.xbmc.kore.ui.widgets.VolumeLevelIndicator.setVolume(boolean, int)' on a null object reference
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at org.xbmc.kore.ui.generic.VolumeControllerDialogFragmentListener.applicationOnVolumeChanged(VolumeControllerDialogFragmentListener.java:159)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at org.xbmc.kore.host.HostConnectionObserver.onVolumeChanged(HostConnectionObserver.java:453)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at org.xbmc.kore.jsonrpc.HostConnection$19.run(HostConnection.java:849)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-09 22:46:22.636 10235 10235 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-09 22:46:22.639  4135  6243 W ActivityManager:   Force finishing activity org.xbmc.kore/.ui.sections.remote.RemoteActivity
```

I can reproduce it on two devices (just repeatedly change volume using the hardware volume up/down buttons).

**Comment by SyncedSynapse** [comment] 2018-06-10 11:46
@poisdeux duplicate of #551?

**Comment by rigid** [comment] 2018-06-10 11:57
right, missed that one.

**Comment by SyncedSynapse** [comment] 2018-06-16 12:13
This seems to still be occurring on the beta. @rigid @poisdeux  can you please confirm. And what steps do you take to trigger the crash? I can't replicate it, but we have reports of crashes on the play console.

**Comment by rigid** [comment] 2018-06-16 12:31
I haven't had a crash since the update. I can paste a logcat if it happens again.

**Comment by poisdeux** [comment] 2018-06-16 19:17
It seems to happen only when `VolumeControllerDialogFragmentListener.applicationOnVolumeChanged` is called. So my guess would be that there is still a fragment listening to application events while its view has been destroyed.
We unregister the application listener in [onDestroy](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/generic/VolumeControllerDialogFragmentListener.java#L126) but first call the `onDestroy` method from the parent. That's where the dialog gets dismissed and this might explain the crashes as the fragment is still listening to application events.
However, I am not able to reproduce the issue in 2.4.1. Which makes this hard to debug...

**Comment by SyncedSynapse** [comment] 2018-06-17 11:52
I can't reproduce it either. @poisdeux I'm not sure that that little race condition (if it is indeed one) would be sufficient to cause so many crashes. Anyway, we can move the `super.onDestroyView()` to the end of the method.

**Comment by poisdeux** [comment] 2018-06-18 10:31
It might be better to move the registration and unregistration to onResume and onPause.
Another thing I just thought of is that the timed dismissal of the dialog might be the cause.
It calls [dismiss] (https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/generic/VolumeControllerDialogFragmentListener.java#L75) on the dialog, which AFAICT doesn't call the onDestroy on the Fragment. We might need to replace this with `dismiss()` from the fragment which dismisses both the fragment and the dialog.

**Comment by poisdeux** [comment] 2018-06-20 19:31
I created a new PR #559 which fixes two issues I could find. However, I'm not sure that this will fix the reported NPEs. I have a feeling there is a race condition we are missing...

**Comment by SyncedSynapse** [comment] 2018-06-22 10:54
Yeah, it still isn't fixed. The good news is that i can replicate it: Make sure you're connected through TCP, use the volume keys to open the volume dialog fragment, then **on Kodi**, keep changing the volume until the dialog closes (use a physical remote or the volume dialog on Kodi). It might take a couple of tries but it crashes

**Comment by SyncedSynapse** [comment] 2018-06-22 17:47
So, AFAICT this is the sequence of events:
1. `VolumeLevelIndicator.onDetachedFromWindow` is called, which calls Butterknife `unbind` therefore making the local `View` references null:
https://github.com/xbmc/Kore/blob/d11dbe68531f8e9f17cbbead11fa4a879eb89ee4/app/src/main/java/org/xbmc/kore/ui/widgets/VolumeLevelIndicator.java#L67

2. `VolumeControllerDialogFragmentListener.onDestroyView` is only called after 1, and it is there that we are unregistering the connection observers:
https://github.com/xbmc/Kore/blob/d11dbe68531f8e9f17cbbead11fa4a879eb89ee4/app/src/main/java/org/xbmc/kore/ui/generic/VolumeControllerDialogFragmentListener.java#L126

So, if between 1) and 2) a volume change occurs **in Kodi** and the connection is through TCP, the TCP listener thread on `HostConnection` will pick it up, notify `HostConnectionObserver`, which will notify `VolumeControllerDialogFragmentListener` (because it hasn't unregistered yet), which will call `setVolume` on `VolumeLevelIndicator`, which will try to access the local View variables that just got set to null...

So, we can:
1) hack it - in `VolumeLevelIndicator.setVolume` check if the variables are null before accessing them
2) find out some other lifecycle methods on `VolumeLevelIndicator` and `VolumeControllerDialogFragmentListener` that work correctly. We need to unregister the observers before any view is destroyed/detached/whatever.

@poisdeux any thoughts on how we could do that, or should we go with the hack

**Comment by poisdeux** [comment] 2018-06-23 15:07
I believe `VolumeLevelIndicator.onDetachedFromWindow` is bounded to `onDestroy`. So moving registration to `onStart` and unregistration to `onStop` should solve this.

**Comment by SyncedSynapse** [comment] 2018-07-04 08:09
Sorry for the late reply. Like i said, i think that the issue is that the lifecycles of the view and the dialog fragment aren't aligned, specifically `VolumeLevelIndicator.onDetachedFromWindow` and `VolumeControllerDialogFragmentListener.onDestroyView`, so we should take care when unbinding to make sure that we don't do it too early.

This led me to question why do we need to `unbind`. AFAICT this just sets the variable to null so it's not stricly necessary. The Butterknife docs don't contain much detail but they just reference unbind in the context of fragments (justifying it by saying that the fragment lifecycle isn't strictly aligned with the activity's...), but we're using it here in the context of a view.
I removed the call to `unbind` in `VolumeLevelIndicator.onDetachedFromWindow`, and it fixes the NPE. The local variables should just be GC when the time comes. PR #563

**Comment by poisdeux** [comment] 2018-07-04 18:56
The unbind in the view is probably redundant. I added the unbind in fragments to solve some memory issues when running the instrumented tests. 

Should we keep this issue open during the next beta run?

**Comment by SyncedSynapse** [comment] 2018-07-05 08:42
I'll close it for now. If it happens in beta i'll reopen it.

**Closed by SyncedSynapse** 2018-07-05 08:42 UTC
