### ISSUE TITLE
Allow volume control without having the app in foreground

### ISSUE THREAD

**Issue by bbastin** [xbmc/Kore#456] opened 2017-09-21 13:12 UTC
Other Kodi remotes like Yatse allow for volume changes while media is being played back without having the app in foreground.

**Solution**: Register the playback with Android's media control API when showing a notification with controls and allow volume control this way.

**Comment by SyncedSynapse** [comment] 2017-09-21 17:59
I don't like this (assuming you're referring to controlling the volume through the physical volume buttons), not even as an option.
The volume buttons are too general, and Kore should only "hijack" them under strict conditions. Right now it's only when the remote panel is showing (and imo it should be kept that way), but i understand that it might also be useful on other screens, but never when Kore is not on the foreground.

**Comment by bbastin** [comment] 2017-09-22 00:01
I often times use Kore as a remote for music or videos running on my TV and think that it would be very convenient to quickly turn the volume up or down without having to unlock or turn on the device. I understand that there are people who do not like this, but having this as an option seems like a good idea to me. I don't see why this shouldn't at least be an option for people like me; maybe you could elaborate on why you think this is a bad idea.

**Comment by poisdeux** [comment] 2017-09-22 07:08
Isn't it possible to add a custom volume slider to the general volume controls from the notification bar? I can't find any API that would allow us to do so. But that would really be awesome if we could simply register our volume control to the generic volume controls.

**Comment by SyncedSynapse** [comment] 2017-09-22 08:06
I'll try to explain my position: Kore is just one more app on your phone, and it's not even one of the most important (generally speaking. You might have an old phone dedicated to the remote, in which case this isn't true, but generally it is). Therefore it should behave as such and shouldn't takeover your phone in marginally related areas, even if it can handle requests in those areas, particularly when that can confuse users.
Regarding the "it could be an option" option, the problem is that we already have an option for that, which makes Kore handle the volume control buttons when it's on the foreground, and that should be kept. Extending that option to handling the volume buttons when in the background is a no go for me, and having another option specifically for that isn't something that i, personally, think should be done. It would be useful to some people, but on the whole i think would be detrimental to the experience.

**Comment by SyncedSynapse** [comment] 2017-09-28 13:20
Closing this, as i don't think that volume control without Kore being on the foreground is something that should be done.

**Closed by SyncedSynapse** 2017-09-28 13:20 UTC
