### ISSUE TITLE
Use hardware volume keys from anywhere inside Kore

### ISSUE THREAD

**Issue by KindKitty** [xbmc/Kore#235] opened 2016-04-26 01:17 UTC
Currently the hardware volume change works only when the remote is open.
It would be useful to be able to change volume using hardware keys also from other parts of the Kore app (e.g.: browsing music/shows).

When I'm browsing media in the app and whatever's playing on Kodi gets to a louder part I go for the hardware keys (to change it quickly) and it doesn't work from there. I then need to wait for the phone volume rocker to get out of the way, select 'remote', and press hardware key again.

Is it possible to change this behaviour?
My neighbors would also benefit from this feature too.

**Comment by Peque** [comment] 2016-10-15 14:36
Duplicate of #157?

**Comment by Peque** [comment] 2016-10-15 14:50
I created a new issue (#298), requesting a more complete media control while the screen is locked (i.e.: volume and playback controls).

**Comment by glenntanner3** [comment] 2017-01-30 19:09
I dont think this is a duplicate, those are different behaviours. I do not want the volume to change when my phone is in my pocket and locked; so that should be a togglable feature. While I have tried to adjust the volume while browsing shows when attempting to add more to the playlist.

**Closed** 2017-10-08 18:48 UTC
