### ISSUE TITLE
When scrolling through playlist, it keeps jumping back to the top

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#754] opened 2020-07-25 17:23 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When scrolling through the current playlist, it keeps jumping back to the top.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I scroll through the current playlist, it stays at the position I scroll to, unless I scroll somewhere else

## Actual Behavior

After less that a second, the playlist scrolls back to the top, making it impossible to view or interact with any content that does not fit on the first page. This happens consistently and reproducibly.

## Possible Fix

This is probably implemented through a list view with an adapter, which scrolls back to the top when refreshed. Suggestions:
* Don’t refresh unless you have to (i.e. content has actually changed)
* When you do need to refresh, try to return to the same position (e.g. remember items in view and scroll back to them). I know Android doesn’t make it easy for you to maintain the position on a list view when refreshing its contents—you have to work around that, e.g. by memorizing an item in view before the update, then returning to it.

### To Reproduce

1. Add a few tracks to the current playlist (at least some 20–30) and start playback
2. In Kore, go to remote control view and swipe left for the playlist
3. Scroll through the playlist (challenge: try to find out what the last item in the playlist is)

### Debuglog

The debuglog can be found here:
Should not be necessary as the behavior should be easy to reproduce. If you have trouble reproducing it, let me know.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Mobile device: OnePlus One
 - Android version: 8.1.0 (LineageOS 15.1.20190226-NIGHTLY-bacon)
 - Kodi version and platform: OSMC 2020.06-1 on RaspberryPi, Kodi 18.7
 - Kore version: 2.5.0 (from F-Droid)
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by poisdeux** [comment] 2020-07-25 18:24
Seems a duplicate of #739. Am I correct?

**Comment by mvglasow** [comment] 2020-07-25 19:14
The behavior is roughly the same as described in #739.

I am using the default options (I believe, as I do not remember changing any of the settings there): connection by IP address, port 80, no TCP, no EventServer. So it looks like I am connecting over HTTP and getting the same issue there.

According to F-Droid, 2.5.0 was added on 2020-02-01; #740 (which should be the fix through #739) was merged on May 25.

I see the successor 2.5.1 is still in pre-release state. If that gets officially released in the near future and pushed out to F-Droid (I suspect the pre-release state is preventing Kore from appearing there), I’ll be happy.

**Closed** 2020-07-26 19:40 UTC
