### ISSUE TITLE
Volume percentage

### ISSUE THREAD

**Issue by wonea** [xbmc/Kore#158] opened 2015-12-24 19:21 UTC
When controlling Kodi as a music player (headless), its not obvious what the current volume is. Only up and down arrows!? A slider or volume percentage would be better.

**Comment by jondo** [comment] 2015-12-24 22:36
I guess this issue is a duplicate of #30.

**Comment by SyncedSynapse** [comment] 2015-12-29 19:36
Duplicate #30

**Closed by SyncedSynapse** 2015-12-29 19:36 UTC
