### ISSUE TITLE
Remote on profile selection menu

### ISSUE THREAD

**Issue by DarkAnakin** [xbmc/Kore#63] opened 2015-04-07 14:18 UTC
I have multiple profile on kodi and it start on profile screen selection, but the app doesn't work until I open one of the profiles.

**Comment by SyncedSynapse** [comment] 2015-04-07 16:59
@Montellese might this be the issue of modal dialogs blocking other threads in Kodi (therefore blocking the thread that handles TCP sockets)?

@DarkAnakin Try this: go into the server configuration (in Kore) and change the TCP port to something that doesn't make sense (1001 for instance) and check if this still happens.

**Comment by MartijnKaijser** [comment] 2015-04-07 17:02
Jsonrpc isn't started yet on login screen iirc.

**Comment by DarkAnakin** [comment] 2015-04-07 19:27
@SyncedSynapse  Nothing change.

@MartijnKaijser Even after log on to a profile and disconnect, the return to the profiles menu makes the remote loose the connection. Or maybe jsonrpc service is stopped at each profile disconnection?

**Comment by MartijnKaijser** [comment] 2015-04-07 19:30
Correct. There's no service during the profile selection screen. There's nothing the remote can do about it

**Comment by Montellese** [comment] 2015-04-07 21:22
What @MartijnKaijser and @DarkAnakin said. The problem is that at the login screen we don't know yet which profile the user wants to load so we don't know which settings to load and therefore we don't turn on the webserver, TCP socket etc.

**Comment by SyncedSynapse** [comment] 2015-04-08 21:35
Question @MartijnKaijser @Montellese : is the EventServer on at that time?

**Comment by Montellese** [comment] 2015-04-09 05:41
IIRC the EventServer is started together with the JSON-RPC TCP server.

**Comment by SyncedSynapse** [comment] 2015-04-15 18:01
Closing this as there's not much that can be done on the remote side.

**Closed by SyncedSynapse** 2015-04-15 18:01 UTC

**Comment by bserrao** [comment] 2015-11-18 03:26
Hi there,
YATSE remote works on profile selection so there is a way to do it... Also I've noticed that when I log out, I still manage to control kodi but only for a few seconds..

**Comment by DrVanScott** [comment] 2016-03-01 20:26
Is there no solution to this? This is what keeps me from switching from yatse to kodi.

**Comment by Tusky** [comment] 2016-03-27 12:47
Yeah it works fine with yatsee. This is really something that's a huge amiss in my eyes if third party can do it, why official app can't is a real mistery

**Comment by kmdm** [comment] 2016-07-06 19:22
+1 - Works in Yatse but not Kore.

**Comment by noxx2015** [comment] 2017-01-12 18:04
have the same problem with my ir-receiver. i use yard2 and yard2 use JSON.
for me: a big no go in Kodi.

**Comment by bisento** [comment] 2017-02-10 12:23
Same problem - I have two profiles (kids and Master)  configured on my RaspberryPi and if I switch between them the connection is lost. I have to plug in an USB keyboard, select the next profile and Enter and after that Kore is picking it up again. This is a major hassle in the living room. Is there any easier way to switch to the kids-profile from my couch without getting up and digging for a physical keyboard?

**Comment by kmdm** [comment] 2017-02-10 12:23
This seems fixed in v2.2.0.

**Comment by bisento** [comment] 2017-02-10 12:26
I am using Kore v 2.2.0 on a android phone (android 7.1.1). Kodi 17 is running on raspPi with libreelec. Does not work for me. Just checked. No switching profiles without physical keyboard. Everything else seems to work just fine... *scratcheshead*

**Comment by kmdm** [comment] 2017-02-10 12:29
Odd, worked for us. We can select profiles with Kore since v2.2.0 and the commit/commits from #311

**Comment by bisento** [comment] 2017-02-10 12:39
just checked: logged in Master user, Kodi 17. I go to close -> Log off master user. Master is locked out and Kore loses connection (switches from "no playback" to "connecting") and pressing up, down enter and so on does not do anything.

**Comment by kmdm** [comment] 2017-02-10 12:42
That's the bit that works for me... I believe showing Connecting... is normal but the arrows/select should work. It uses the EventServer instead of the JSON-RPC API as far as I know. (Which is what Yatse does also - does Yatse work?)

**Comment by bisento** [comment] 2017-02-10 12:44
i attached the keyboard (usb), selected kids-profile and after successful switching the profile Kore connected and is responsive again. Did not check Yatse yet. ( I am using F-droid repository and do not have google apps installed)

**Comment by kmdm** [comment] 2017-02-10 12:59
You can check the settings here (probably best under the Master profile):

http://yatse.tv/redmine/projects/yatse/wiki/XbmcConfig

**Comment by kmdm** [comment] 2017-02-10 13:14
I think the important one is:-

"Allow programs on other systems to control Kodi"

(or words to that effect)

**Comment by bisento** [comment] 2017-02-10 13:22
i just checked. This point was not activated. I activated it in both profiles (physical keyboard ftw!), did a restart of the raspPi and of Kore... nothing different. as soon as I switch the profile and the screen with the profile selection is displayed Kore loses the connection and I have to resort to the keyboard. *sigh*

**Comment by kmdm** [comment] 2017-02-10 13:24
Kore will show "Connecting..." but the arrows/enter/select should work... Does Kodi (now) listen on 9777?

E.g.

# netstat -lnup | grep 9777
udp        0      0 0.0.0.0:9777            0.0.0.0:*                           11174/kodi.bin

**Comment by bisento** [comment] 2017-02-10 13:26
# netstat -lnup | grep 9777
udp        0      0 :::9777                 :::*                                350/kodi.bin

**Comment by kmdm** [comment] 2017-02-10 13:29
Well, I'm at somewhat of loss, here:-

* The eventserver is active (9777); and
* We have Kore v2.2.0; and
* Even though Kore shows Connecting... after the profile screen;
* It can still operate the arrows/select button to pick a profile.

**Comment by bisento** [comment] 2017-02-10 13:37
hmm... thanks for your help. looks like I have to deal with it. I was hoping I could ditch the keyboard - it has a very low WAF (womans acceptance factor) ;-)

**Comment by kmdm** [comment] 2017-02-10 13:37
No HDMI-CEC options? That works for me (when the -CEC stuff doesn't fall over on my Cubox i4pro) 

(E.g. using the TV control)

**Comment by bisento** [comment] 2017-02-10 13:50
ok, i just installed Yatse. It works with yatse. Sorry for Kore, but Yatse it is then.
For future reference for people without GAPPS or playstore access: one can download Yatse (or any other APK from the playstore) by using Raccoon on PC (http://onyxbits.de/raccoon). This helped.

**Comment by kmdm** [comment] 2017-02-10 13:56
What's completely odd is that Kore v2.2.0 on the profile screen should be using the same mechanism (eventserver) that yatse uses. 

Oh well, glad you have something working at least!

**Comment by bisento** [comment] 2017-02-10 13:57
thanx for your really fast response and input. kudos to you!

**Comment by SyncedSynapse** [comment] 2017-02-10 14:26
Did you check if Kore is trying to use the EventServer? In Kore, gop to the media center settings, select the "Use EventServer" checkbox and save. Then, double check that it remains selected.

**Comment by kmdm** [comment] 2017-02-10 14:27
(I didn't check that [or remember it was there]!)

**Comment by bisento** [comment] 2017-02-10 14:31
it works! Thanks a lot! this should be written in 48 pt font or more across the frontpage or something! This was really hard to find! Many thanks!

**Comment by bisento** [comment] 2017-02-10 14:33
"use Eventserver" in the media centre setings in Kore was the solution (in case someone is wondering)

**Comment by kmdm** [comment] 2017-02-10 14:34
@bisento As well as the option to enable the EventServer in kodi, I'd venture.

**Comment by Megachip** [comment] 2017-06-07 14:47
Not working with [Official Kodi Remote](http://kodi.wiki/view/Official_Kodi_Remote/iOS) nor with [Sybu Kodi](https://itunes.apple.com/us/app/sybu-for-kodi-and-xbmc/id567524653?mt=8).
Yatse works fine. Any working iOS Remote?

**Comment by david-morris** [comment] 2021-12-07 18:28
Hey, could somebody reopen this?  It doesn't seem like this feature should depend on remote particulars.  There should at least be an option to carry over the left, right, and select mappings from the master profile's config.

If I made such a PR, would there be interest?
