### ISSUE TITLE
Allow volume changes with hardware keys even while screen is off

### ISSUE THREAD

**Issue by ThiefMaster** [xbmc/Kore#157] opened 2015-12-23 22:49 UTC
I didn't even know that this is possible, but my audiobook player app has this annoying feature that even when the phone is locked and the screen is off the volume buttons change the playback volume. But while it's annoying in this app, I think it would be a great feature (maybe with an option to toggle it) in Kore.

There are many movies with some very loud and some very quiet scenes and having to unlock the phone to change the volume is not very nice. Being able to use the volume keys immediately would be pretty useful for this.

**Comment by JoseFSilva** [comment] 2016-04-26 01:05
+1 
I also feel this would be a nice improvement to have.
I currently work around this by having the screen always on when using Kore, which is not good at all for the phone's battery life/health :/

**Comment by Peque** [comment] 2016-10-15 14:37
Duplicate of #235? :wink:

**Comment by Peque** [comment] 2016-10-15 14:50
I created a new issue (#298), requesting a more complete media control while the screen is locked (i.e.: volume and playback controls).

**Closed** 2022-09-22 08:34 UTC
